### ISSUE TITLE
Aperture growth apodization for curvilinear arrays

### ISSUE THREAD

**Issue by l-l-z** [thorstone25/qups#10]
When I tried using the aperture growth apodization function with a curvilinear transducer (TransducerConvex), I got a warning that only linear arrays (TransducerArray) are currently supported. Are you planning on expanding the implementation of that apodization function to include curvilinear transducers in the near future?

**Comment by thorstone25** [comment]
We can add that as a feature, yes. It's a trivial extension as you would only need to switch from a definition based on depth vs. width to depth vs. angle I believe. I can't promise a timeline for when I would be able to do that myself though.
