### ISSUE TITLE
Error using example_.m

### ISSUE THREAD

**Issue by recordMing** [thorstone25/qups#18]
Error using example_ (line 57)
Error setting default value of property 'impulse' of class 'Transducer':
Undefined function 'mustBeScalarOrEmpty' for input arguments of type 'Waveform'.

**Comment by thorstone25** [comment]
It appears you aren't on R2020b or later if you don't have the (`mustBeScalarOrEmpty`)[https://www.mathworks.com/help/matlab/ref/mustbescalarorempty.html] validator function.

If that isn't an option, you can either define the validator yourself, or just delete the `mustBeX` validators that are undefined in R2020a or R2019b.

**Comment by recordMing** [comment]
Hope you are well.


Thank you kindly, the problem has been solved.&nbsp;


Could you help explain what "kmedium_iso" means in UltragroundSystem.m? or whether there are relevant references? I would be very grateful if you could help me.


Thanks and regards.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thorstone25/qups"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月9日(星期五) 中午12:24
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [thorstone25/qups] Error using example_.m (Issue #18)





 
It appears you aren't on R2020b or later if you don't have the (mustBeScalarOrEmpty)[https://www.mathworks.com/help/matlab/ref/mustbescalarorempty.html] validator function.
 
If that isn't an option, you can either define the validator yourself, or just delete the mustBeX validators that are undefined in R2020a or R2019b.

**Comment by thorstone25** [comment]
Since this toolbox is primarily meant for pulse-echo ultrasound, it runs a background simulation to remove some certain propagation and modelling artifacts.

It does that by running a "isoimpedance" simulation, where the impedance is constant, therefore no reflections occur. That removes reflections off the boundaries of the simulation or direct propagation from source to receiver through where the transducer would be, for example.
