### ISSUE TITLE
Very strange bug

### ISSUE THREAD

**Issue by tomelse** [thorstone25/qups#37]
Hi :) I'm the reviewer for JOSS ([#6772](https://github.com/openjournals/joss-reviews/issues/6772)).

I think I've found a slightly bizarre bug... On my linux system, my home directory is the following (anonymised): `/home/xyz.cxyz.org/name`. When trying to run your tests, it means that I get the following error: 

```
** Starting compile_mex_msfm2d
## -----------------------------------------------------------------------------
## Error occurred in 'compile_mex_msfm2d' and it did not run to completion.
##   Identifier: 'MATLAB:mex:AccessDenied'
##      Message: Access denied; check that you have permissions to access '/home/xyz.mexa64xyz.org/name/Documents/qups/bin'.
##        Stack: /usr/local/MATLAB/R2024a/toolbox/matlab/buildtool/ext/+matlab/+buildtool/+tasks/MexTask.m (MexTask.buildMex) at 172
## -----------------------------------------------------------------------------
** Failed compile_mex_msfm2d
```

I've tracked it down to this line, I think: `ofls = replace(fullfile(base, "bin", nms), '.c', "."+mexext());`. Clearly you were expecting the path to end in .c, I guess, but by some quirk it is in my home directory path.

**Comment by tomelse** [comment]
My MATLAB skills are not up to scratch to fix this so I'll finish off the review once you've updated the git repo :)

**Comment by tomelse** [comment]
Okay I've managed to hack it to work on my local PC, replacing the following line (line 84 in buildfile.m).

```
oils = replace(fullfile(base, "bin", nms), ".c", "."+mexext());
```

I replaced with:

```
for i = 1:numel(nms)
[~, stem] = fileparts(nms(l));
ofls(i) = fullfile(base, "bin", stem+"."+mexext());
end
```

**Comment by thorstone25** [comment]
Hmm, very strange indeed -  I'm noticing though that the erroring path starts with
`/home/xyz**.mexa64**xyz.org ...`
- I'm guessing some folder in the path matched the `".c"` token.
This looks like a bit of a corner case, but a bug for sure, glad you caught it!

**Comment by tomelse** [comment]
Thanks! Definitely a weird edge case, but I think a good reminder that we should use specialised file path libraries rather than string operations for these sorts of things
