### ISSUE TITLE
Beamforming Walkthrough

### ISSUE THREAD

**Issue by tomelse** [thorstone25/qups#40]
The first two lines of `beamforming_walkthrough.mlx` do not work in the way that I would expect. 

I'm not an expert in MATLAB, but I would expect to be able to run the walkthroughs without starting a new project. 

The function `openProject(which("Qups.prj"))` doesn't seem to return anything either, it seems like Qups.prj doesn't exist on my computer, or at least isn't on the path?

[JOSS Review #6772](https://github.com/openjournals/joss-reviews/issues/6772)

**Comment by tomelse** [comment]
There's also some placeholders for the linear acoustic equation etc.

**Comment by tomelse** [comment]
The verasonics data is also not included in the import example. This isn't a problem given the data file is probably too big to store on GitHub. It would be nice if you could provide an example dataset that people could use here though.

**Comment by thorstone25** [comment]
> The first two lines of `beamforming_walkthrough.mlx` do not work in the way that I would expect.
> 
> I'm not an expert in MATLAB, but I would expect to be able to run the walkthroughs without starting a new project.
> 
> The function `openProject(which("Qups.prj"))` doesn't seem to return anything either, it seems like Qups.prj doesn't exist on my computer, or at least isn't on the path?
> 
> [JOSS Review #6772](https://github.com/openjournals/joss-reviews/issues/6772)

The `Qups.prj` file is in the base directory of the repo. I'm not sure why it wasn't found by the `which` command if that directory was on the path? If you ran it from another folder though, then perhaps it wasn't on the path? Would it be clearer if that line was removed?

**Comment by tomelse** [comment]
I realised the problem actually is if you don't have a project open, the `~=` comparison does not work as intended. Sorry I can't provide the exact code right now as I'm not on my laptop.

**Comment by thorstone25** [comment]
> The verasonics data is also not included in the import example. This isn't a problem given the data file is probably too big to store on GitHub. It would be nice if you could provide an example dataset that people could use here though.

Yes, that data gets very large! That's a good suggestion, I'll look into uploading some example data.

**Comment by thorstone25** [comment]
> I realised the problem actually is if you don't have a project open, the `~=` comparison does not work as intended. Sorry I can't provide the exact code right now as I'm not on my laptop.

Oh, I see it - that is a bug!
