### ISSUE TITLE
Example of Eikonal beamforming

### ISSUE THREAD

**Issue by waltsims** [thorstone25/qups#9]
Would it be possible to have an example of Eikonal beam-forming with heterogeneous sound speed fields? Seems unsupported for now.

**Comment by thorstone25** [comment]
Yes, I think we can make that part of the k-wave example, as you'll need a FDTD simulator to run an example with a distributed sound speed. The signature for those functions also needs a major update / rewrite.

**Comment by thorstone25** [comment]
There's currently an example of Eikonal delay beamforming in the `example.mlx` and `example_.m` scripts. Generating heterogenous data is still a work-in-progress as the k-Wave interface needs some refactoring to make it clearer.

**Comment by thorstone25** [comment]
This has been addressed as of (passing) commit 2794fea0c64670b93571086b0f276bc2438e167a. The example relies on a working kWave installation in order to generate heterogeneous data via the kWave installation.
